const constants = {
  INCREMENT: 'INCREMENT',
  FETCH_DEVICES_BEGIN: 'FETCH_DEVICES_BEGIN',
  FETCH_DEVICES_SUCCESS: 'FETCH_DEVICES_SUCCESS',
  FETCH_DEVICES_ERROR: 'FETCH_DEVICES_ERROR'
}

export default constants
