const constants = {
  INCREMENT: 'INCREMENT',
  FETCH_DEVICES_BEGIN: 'FETCH_DEVICES_BEGIN',
  FETCH_DEVICES_SUCCESS: 'FETCH_DEVICES_SUCCESS',
  FETCH_DEVICES_ERROR: 'FETCH_DEVICES_ERROR',
  TOGGLE_MODAL: 'TOGGLE_MODAL'
}

export default constants
